# DO NOT EDIT THIS FILE

SUBMIT  := \
	src/Dictionary.java \
	src/FileCorrector.java \
	src/SwapCorrector.java \
	src/TokenScanner.java \
	src/SpellChecker.java \
	src/Levenshtein.java \
	test/MyTests.java

JAVAC	:= javac

DEPENDS := src/*.java

TESTS := \
	test/DictionaryTest.java \
	test/LevenshteinTest.java \
	test/SpellCheckerTest.java \
	test/TokenScannerTest.java \
	test/FileCorrectorTest.java \
	test/MyTests.java \
	test/SwapCorrectorTest.java

HWNAME := hw08
ts := $(shell /bin/date "+%Y-%m-%d-%H:%M:%S")

ZIPNAME := $(HWNAME)-submit($(ts)).zip

.PHONY: all SpellChecker clean zip

all:	

bin:
	mkdir bin

runCmd: $(DEPENDS) bin
	java -cp bin SpellCheckerRunner files/Gettysburg.txt files/Gettysburg-out.txt files/dictionary.txt files/misspellings.txt

runGUI : $(DEPENDS) bin
	java -cp spellcheck-gui.jar:bin SpellCheckerGUI

SpellChecker : $(DEPENDS) bin
	$(JAVAC) -d bin $(DEPENDS)

zip: $(SUBMIT)
	zip '$(ZIPNAME)' $(SUBMIT)

clean:
	rm -f src/*.class bin/* test/*.class
	rm -rf *.zip
